version: 2

sources:
  - name: raw
    database: "{{ env_var('SNOWFLAKE_DATABASE', 'ENTERPRISE_PLATFORM') }}"
    schema: RAW
    tables:
      - name: raw_customers
      - name: raw_orders

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]
  - name: mart_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]
