-- Snowflake bootstrap for the Enterprise Data Platform demo.
-- Run as ACCOUNTADMIN once, then use PLATFORM_ROLE for day-to-day work.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS PLATFORM_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS ENTERPRISE_PLATFORM;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_PLATFORM.RAW;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_PLATFORM.STAGING;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_PLATFORM.MARTS;

CREATE ROLE IF NOT EXISTS PLATFORM_ROLE;
GRANT USAGE ON WAREHOUSE PLATFORM_WH TO ROLE PLATFORM_ROLE;
GRANT USAGE ON DATABASE ENTERPRISE_PLATFORM TO ROLE PLATFORM_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA ENTERPRISE_PLATFORM.RAW TO ROLE PLATFORM_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA ENTERPRISE_PLATFORM.STAGING TO ROLE PLATFORM_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA ENTERPRISE_PLATFORM.MARTS TO ROLE PLATFORM_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA ENTERPRISE_PLATFORM.RAW TO ROLE PLATFORM_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA ENTERPRISE_PLATFORM.STAGING TO ROLE PLATFORM_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA ENTERPRISE_PLATFORM.MARTS TO ROLE PLATFORM_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA ENTERPRISE_PLATFORM.RAW TO ROLE PLATFORM_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA ENTERPRISE_PLATFORM.STAGING TO ROLE PLATFORM_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA ENTERPRISE_PLATFORM.MARTS TO ROLE PLATFORM_ROLE;

-- Demo user. Replace the placeholder before running this statement.
-- For production use key-pair authentication/OAuth and a secret manager.
CREATE USER IF NOT EXISTS PLATFORM_APP
  PASSWORD = 'CHANGE_ME_IMMEDIATELY'
  DEFAULT_ROLE = PLATFORM_ROLE
  DEFAULT_WAREHOUSE = PLATFORM_WH
  DEFAULT_NAMESPACE = ENTERPRISE_PLATFORM.RAW
  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE PLATFORM_ROLE TO USER PLATFORM_APP;

USE ROLE PLATFORM_ROLE;
USE WAREHOUSE PLATFORM_WH;
USE DATABASE ENTERPRISE_PLATFORM;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS RAW_CUSTOMERS (
  customer_id NUMBER,
  full_name VARCHAR,
  email VARCHAR,
  country VARCHAR,
  source_file VARCHAR,
  loaded_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_ORDERS (
  order_id NUMBER,
  customer_id NUMBER,
  amount NUMBER(18,2),
  status VARCHAR,
  updated_at TIMESTAMP_TZ,
  source_file VARCHAR,
  loaded_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_ORDER_EVENTS (
  event_id VARCHAR,
  event_type VARCHAR,
  event_ts TIMESTAMP_TZ,
  order_id NUMBER,
  customer_id NUMBER,
  amount NUMBER(18,2),
  status VARCHAR,
  channel VARCHAR,
  region VARCHAR,
  schema_version NUMBER,
  raw_payload VARIANT,
  loaded_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
