version: 2
models:
  - name: stg_customers
    columns:
      - name: master_customer_id
        tests: [not_null, unique]
      - name: email
        tests: [not_null]
  - name: stg_customer_xref
    columns:
      - name: source_customer_id
        tests: [not_null, unique]
      - name: master_customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: master_customer_id
  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_customer_xref')
              field: source_customer_id
  - name: mart_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]
