name: enterprise_platform_snowflake
version: '1.0.0'
config-version: 2
profile: enterprise_platform_snowflake
model-paths: ['models']
models:
  enterprise_platform_snowflake:
    staging:
      +schema: STAGING
      +materialized: view
    marts:
      +schema: MARTS
      +materialized: view
